server:
  port: 8080

jasypt:
  encryptor:
    password: lybbs

spring:
  datasource:
    url: jdbc:mysql://81.68.228.150:3306/ly_bbs?useSSL=false&characterEncoding=utf8&autoReconnect=true
    username: root
    password: ENC(1sgY0XbWMGTszXVvFPNM/hRwd5m+3Stm)
  freemarker:
    tempalte-loader-path: classpath:/templates/
  data:
    elasticsearch:
      cluster-name: article-search
      cluster-nodes: 47.244.9.82:9300
#    prefer-file-system-access: false
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    suffix: .ftl
#    settings:
#      template_exception_handler: rethrow
#      number_format: 0.##
#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    static-locations: ["classpath:/static/"]

# 配置mapper.xml位置，这个位置可以在pom.xml里配置
mybatis-plus:
  mapper-locations: classpath:com/lengyan/lybbs/mapper/*Mapper.xml

# 想看mybatis执行的sql的时候，去掉下面这段的注释
#logging:
#  level:
#    com:
#      lengyan:
#        lybbs:
#          mapper: debug

